name: Nightly builds

on:
  schedule: # Run every day at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # only run this build in the main repository, not in forks
    if: github.repository == 'rpo-fr/oauth2-proxy'
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: feature/nuxeo
        fetch-depth: 0
        fetch-tags: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to docker.cloud.keendoo.work
      uses: docker/login-action@v2
      with:
        registry: docker.cloud.keendoo.work/oauth2-proxy
        username: ${{ secrets.REGISTRY_USERNAME_NIGHTLY }}
        password: ${{ secrets.REGISTRY_PASSWORD_NIGHTLY }}

    - name: Build images
      run: |
        make docker-nightly-build

    - name: Push images
      run: |
        make docker-nightly-push
